# -*- coding: utf-8 -*-
"""scapper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1zOywuJQpBX0Hl1lkWYTKDsMNF6XT3H
"""

# scraper.py

import requests
from bs4 import BeautifulSoup
import re
import json
import spacy
import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from datetime import datetime

nlp = spacy.load("en_core_web_sm")

def scrape_karkidi_jobs(keyword="data science", pages=2):
    # ... (your scraping code here)

def preprocess_skills(skills):
    # ... (your preprocessing code here)

def vectorize_jobs(job_data):
    # ... (your vectorization code here)

def cluster_jobs(X, n_clusters=8):
    # ... (your clustering code here)

def save_model(vectorizer, model):
    # ... (your model saving code here)

def load_model():
    # ... (your model loading code here)

def classify_new_job(job_skills):
    # ... (your classification code here)

def run_pipeline(keyword="data science", pages=2, n_clusters=8):
    # ... (your pipeline code here)